### ISSUE TITLE
Issue with @@INLINE@@ and escaping

### ISSUE THREAD

**Issue by maxime-esa** [AdaCore/templates-parser#37]
Hi,

Two consecutive escaping in an `@@INLINE@@` statement provoke a runtime exception:
```
@@INLINE(      \()(,\n       )(\)\))@@
```

The `\)\)` to have two closing parentheses make the library crash
If you put a space between the two, it does not crash (but results in undesired output)

The stack trace:
```
Templates_Parser.Load.Get_Tag_Parameter_Count at templates_parser.adb:2911
Templates_Parser.Load.Parse at templates_parser.adb:3700
Templates_Parser.Load.Parse at templates_parser.adb:3781
...
```

**Comment by TurboGit** [comment]
Fixed, thanks for reporting this issue.

**Comment by maxime-esa** [comment]
Thanks!
