### ISSUE TITLE
Handling of indentation in tables

### ISSUE THREAD

**Issue by maxime-esa** [AdaCore/templates-parser#4]
I am trying to render multi-line Tags, but I think there is an issue with the handling of indentation.
For example, if my Tag `FooBar` contains these elements:

1=>
```
"--  Hello
--  World"
```
(2 lines)
2=>
```
"procedure Foo is
begin"
```
(also 2 lines)

If I write my template like this:
```
@@TABLE@@
          @_FooBars_@
@@END_TABLE@@
```

I would expect that all elements of the list are indented at the same level:
```
          --  Hello
          --  World
          procedure Foo is
          begin
```
However, what I get is:
```
          -- Hello
--  World
         procedure Foo is
begin
```
I did not find a way to ensure the alignment of all lines automatically...
I hope that's clear. Let me know if you need concrete code to reproduce.

**Comment by TurboGit** [comment]
Your two lines are separated with an CR?

I think this is expected. The tag expansion code does not know what is the current indentation. So you have only both first lines at the right indentation. I don't see a solution.

**Comment by maxime-esa** [comment]
I think this is a very useful feature to add. I have worked in the past with StringTemplate which does this auto-indentation by default (see https://github.com/antlr/stringtemplate4/blob/master/doc/indent.md) ; whenever you need to generate code, this becomes mandatory, as you typically want to have a template like this:
```
@@TABLE@@
void @_functionName_@ {
    @_Statements_@
}
@@END_TABLE@@
```
where `@_Statement_@` is generated from another template, and contain several lines.

Is it possible to add a filter `AUTO_INDENT` to "Statements" (like this: `@_AUTO_INDENT:Statements_@`) that could know the current indent level and that could apply it to the current tag line by adding whitespaces after each CR ? (I think that's how StringTemplate does it)

**Comment by maxime-esa** [comment]
Closing, now it is implemented. Thanks!
