### ISSUE TITLE
Binder -V option issue.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/templates-parser#40]
Hello,
My configuration is GNAT Community 2020 on macOS Catalina.
I have the following issue from master branch:
```
% make
...
Bind
   [gprbind]      templates2ada.bexch
   [gprbind]      templatespp.bexch
   [Ada]          templates2ada.ali
   [Ada]          templatespp.ali
b__templates2ada.adb:67:09: (Ada 2005) non-graphic character not permitted in string literal
b__templatespp.adb:67:09: (Ada 2005) non-graphic character not permitted in string literal
gprbind: compilation of binder generated file failed
gprbind: compilation of binder generated file failed
```
It seems that the binder -V option provoques this issue. It's ok without.
HTH, Pascal.

**Comment by TurboGit** [comment]
And what is on line 67 of b__templates2ada.adb and b__templatespp.adb ? Maybe this will help understanding what is going wrong. Thanks.

**Comment by Blady-Com** [comment]
I don't guess it is related to TP but rather to gnatbind, the lines are the same for both files:
   Bind_Env : aliased constant String :=
       "["07"]version" & "["04"]20.0"
     & ASCII.NUL;

**Comment by maxime-esa** [comment]
Just for info the same bug happens on Linux with GNAT CE 2020, had to revert to an older version of GNAT.

**Comment by TurboGit** [comment]
This is now fixed on our side. So I'm closing this issue. Thanks for reporting.

**Comment by Blady-Com** [comment]
What was the bug fix?

**Comment by TurboGit** [comment]
This fix has been to replace the non-graphic characters in string literal by equivalent Character'Val().
