### ISSUE TITLE
Cursor tag of dimension 1 and length 1 should be processed as standard tag instead of being ignored 

### ISSUE THREAD

**Issue by dsauvage** [AdaCore/templates-parser#42]
**Description**
Cursor tag of dimension 1 and length 1 ignored instead of being processed as standard tag

**Reproducer**
[tp-curors.tar.gz](https://github.com/AdaCore/templates-parser/files/5738817/tp-curors.tar.gz)
```
$ tar -xvzf tp-cursors.tar.gz
$ cd tp-cursors
$ make
 ```
**Patch**
[tp-cursor.patch.txt](https://github.com/AdaCore/templates-parser/files/5738825/tp-cursor.patch.txt)

**Comment by TurboGit** [comment]
Thanks, working on integrating this.
