### ISSUE TITLE
DEFAULT_LIBRARY_TYPE shared is not accepted

### ISSUE THREAD

**Issue by atupone** [AdaCore/templates-parser#65]
Looking at the Makefile seems that the allowed values for DEFAULT_LIBRARY_TYPE is shared and static.

`ifeq ($(DEFAULT_LIBRARY_TYPE),shared)`

but shared is not a value accepted by tp_shared.gpr. The value there is  relocatable

**Comment by TurboGit** [comment]
The makefile is checking the variable `DEFAULT_LIBRARY_TYPE` but in the project file it is `LIBRARY_TYPE` which is passed as gprbuild's parameter. So to me there is no issue.

I'll close, if you have a problem I'll reopen.
